services:
  db:
    networks:
      - net
    image: mysql:8
    ports:
      - 3386:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=pwd
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_CHARSET=utf8mb4

  nginx:
    build:
      context: ./../.
      dockerfile: ./docker/nginx/Dockerfile
      target: local
    networks:
      - net
    ports:
      - 8080:80
    volumes:
      - ./../:/php-app

  php:
    user: '1000'
    init: true
    build:
      context: ./../.
      dockerfile: ./docker/php/Dockerfile
      target: local
    networks:
      - net
    volumes:
      - ./../:/php-app
    environment:
      - COMPOSER_CACHE_DIR=/php-app/storage/cache/.composer

volumes:
  db: {}
